# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SVGCompCreator.ui'
#
# Created: Sat Nov  9 11:15:14 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(700, 400)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.svg_canvas = SvgView(self.centralwidget)
        self.svg_canvas.setObjectName(_fromUtf8("svg_canvas"))
        self.horizontalLayout_2.addWidget(self.svg_canvas)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_schematic = QtGui.QWidget()
        self.tab_schematic.setObjectName(_fromUtf8("tab_schematic"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_schematic)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.tab_schematic)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.txt_label = QtGui.QLineEdit(self.tab_schematic)
        self.txt_label.setObjectName(_fromUtf8("txt_label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.txt_label)
        self.label_3 = QtGui.QLabel(self.tab_schematic)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.spnbox_pincount = QtGui.QSpinBox(self.tab_schematic)
        self.spnbox_pincount.setMaximumSize(QtCore.QSize(42, 16777215))
        self.spnbox_pincount.setMaximum(100)
        self.spnbox_pincount.setObjectName(_fromUtf8("spnbox_pincount"))
        self.horizontalLayout_5.addWidget(self.spnbox_pincount)
        self.label_8 = QtGui.QLabel(self.tab_schematic)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.spn_add_width = QtGui.QSpinBox(self.tab_schematic)
        self.spn_add_width.setObjectName(_fromUtf8("spn_add_width"))
        self.horizontalLayout_5.addWidget(self.spn_add_width)
        self.label_9 = QtGui.QLabel(self.tab_schematic)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_5.addWidget(self.label_9)
        self.spn_add_height = QtGui.QSpinBox(self.tab_schematic)
        self.spn_add_height.setObjectName(_fromUtf8("spn_add_height"))
        self.horizontalLayout_5.addWidget(self.spn_add_height)
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.tbl_schematic = QtGui.QTableView(self.tab_schematic)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tbl_schematic.sizePolicy().hasHeightForWidth())
        self.tbl_schematic.setSizePolicy(sizePolicy)
        self.tbl_schematic.setObjectName(_fromUtf8("tbl_schematic"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.tbl_schematic)
        self.horizontalLayout.addLayout(self.formLayout)
        self.tabWidget.addTab(self.tab_schematic, _fromUtf8(""))
        self.tab_pcb = QtGui.QWidget()
        self.tab_pcb.setObjectName(_fromUtf8("tab_pcb"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_pcb)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_7 = QtGui.QLabel(self.tab_pcb)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.tab_pcb)
        self.label_5.setStatusTip(_fromUtf8(""))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.txt_spacing_h = QtGui.QLineEdit(self.tab_pcb)
        self.txt_spacing_h.setMaximumSize(QtCore.QSize(40, 16777215))
        self.txt_spacing_h.setStatusTip(_fromUtf8(""))
        self.txt_spacing_h.setObjectName(_fromUtf8("txt_spacing_h"))
        self.horizontalLayout_4.addWidget(self.txt_spacing_h)
        self.label_2 = QtGui.QLabel(self.tab_pcb)
        self.label_2.setStatusTip(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.txt_spacing_v = QtGui.QLineEdit(self.tab_pcb)
        self.txt_spacing_v.setMaximumSize(QtCore.QSize(40, 16777215))
        self.txt_spacing_v.setStatusTip(_fromUtf8(""))
        self.txt_spacing_v.setObjectName(_fromUtf8("txt_spacing_v"))
        self.horizontalLayout_4.addWidget(self.txt_spacing_v)
        spacerItem1 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_4.setStretch(4, 1)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.groupBox_mount = QtGui.QGroupBox(self.tab_pcb)
        self.groupBox_mount.setTitle(_fromUtf8(""))
        self.groupBox_mount.setObjectName(_fromUtf8("groupBox_mount"))
        self.layout_2 = QtGui.QHBoxLayout(self.groupBox_mount)
        self.layout_2.setObjectName(_fromUtf8("layout_2"))
        self.radio_smd = QtGui.QRadioButton(self.groupBox_mount)
        self.radio_smd.setObjectName(_fromUtf8("radio_smd"))
        self.layout_2.addWidget(self.radio_smd)
        self.radio_tht = QtGui.QRadioButton(self.groupBox_mount)
        self.radio_tht.setChecked(True)
        self.radio_tht.setObjectName(_fromUtf8("radio_tht"))
        self.layout_2.addWidget(self.radio_tht)
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.groupBox_mount)
        self.tbl_pcb = QtGui.QTableView(self.tab_pcb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tbl_pcb.sizePolicy().hasHeightForWidth())
        self.tbl_pcb.setSizePolicy(sizePolicy)
        self.tbl_pcb.setObjectName(_fromUtf8("tbl_pcb"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.tbl_pcb)
        self.horizontalLayout_3.addLayout(self.formLayout_2)
        self.tabWidget.addTab(self.tab_pcb, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.txt_silkscreen = SvgPathEdit(self.tab)
        self.txt_silkscreen.setObjectName(_fromUtf8("txt_silkscreen"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.txt_silkscreen)
        self.list_path_cmds = QtGui.QListWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.list_path_cmds.sizePolicy().hasHeightForWidth())
        self.list_path_cmds.setSizePolicy(sizePolicy)
        self.list_path_cmds.setObjectName(_fromUtf8("list_path_cmds"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.list_path_cmds)
        self.horizontalLayout_6.addLayout(self.formLayout_3)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExport = QtGui.QAction(MainWindow)
        self.actionExport.setObjectName(_fromUtf8("actionExport"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionExport)
        self.menuHelp.addAction(self.actionHelp)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "SVG component creator", None))
        self.label.setText(_translate("MainWindow", "Part name", None))
        self.label_3.setText(_translate("MainWindow", "Connectors", None))
        self.label_8.setText(_translate("MainWindow", "Add width", None))
        self.label_9.setText(_translate("MainWindow", "Add height", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_schematic), _translate("MainWindow", "Schematic", None))
        self.label_7.setText(_translate("MainWindow", "Spacing", None))
        self.label_5.setText(_translate("MainWindow", "Horisontal", None))
        self.label_2.setText(_translate("MainWindow", "Vertical", None))
        self.radio_smd.setText(_translate("MainWindow", "Surface mount", None))
        self.radio_tht.setText(_translate("MainWindow", "Through hole", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_pcb), _translate("MainWindow", "Footprint", None))
        self.label_4.setText(_translate("MainWindow", "Silkscreen path", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Silkscreen", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionExport.setText(_translate("MainWindow", "Export...", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))
        self.actionSave.setText(_translate("MainWindow", "Save...", None))
        self.actionLoad.setText(_translate("MainWindow", "Load...", None))

from SvgView import SvgView
from SvgPathEdit import SvgPathEdit
